baseURL: ""
languageCode: en-us
title: Demo for Hugo
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello Stranger \U0001F44B"
    Content: Welcom to my blog. here you'll find a lot of cool information about a cool stuff
  socialIcons:
    - name: facebook
      url: 'www.facebook.com'
    - name: twitter
      url: 'www.twitter.com'
    - name: github
      url: 'www.github.com' 
    - name: linkedin
      url: 'www.linkedin.com'
    - name: discord
      url: ''
    - name: instagram 

  cover:
    linkFullImages: true

  ShowBreadCrumbs : true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: archives
      url: /archives/
      weight: 20
      
